import React from 'react'
import Container from '../Container'

const ProductIndex = () => {
  return (
    <Container>
      <h3>Products</h3>
      <div className="div-table-responsive">
        <table className='table table-striped'>
          <thead>
            <tr>
              <th>ACTION</th>
              <th>ITEMNAME</th>
              <th>UOM</th>
              <th>AMOUNT</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
            <tr>
              <td>ACTION</td>
              <td>ITEMNAME</td>
              <td>UOM</td>
              <td>AMOUNT</td>
            </tr>
          </tbody>
        </table>
      </div>
    </Container>
  )
}

export default ProductIndex